- hosts: "{{ hosts }}"
  collections:
    - arubanetworks.aoscx_command
  gather_facts: False  
  tasks:
    - name: Upload firmware to partition through HTTP
      aoscx_command:
        partition_name: "{{ partition }}"
        remote_firmware_file_path: "{{ remote_firmware_file_path }}"
        vrf: 'mgmt'
