- hosts: "{{ hosts }}"
  tasks:
  - name: Upload firmware to partition through HTTP
    arubanetworks.aoscx.aoscx_upload_firmware:
      partition_name: "{{ partition }}"
      remote_firmware_file_path: "{{ remote_firmware_file_path }}"
      vrf: 'mgmt'
