- hosts: "{{ hosts }}"

  become: yes
  tasks:

    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: install core packages
      apt:
        name:
          - qemu-guest-agent
        update_cache: yes

    - name: start guest qemu-guest-agent
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    - name: Set the timezone
      ansible.builtin.command:
        cmd: timedatectl set-timezone Europe/Oslo
        
    - name: Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Ensure ufw is enabled
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true

    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled

    - name: Deny all incoming traffic by default
      community.general.ufw:
        default: deny
        direction: incoming

    - name: Allow OpenSSH rule
      community.general.ufw:
        rule: allow
        name: OpenSSH
        
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
