- hosts: "{{ hosts }}"

  become: yes
  tasks:

    - name: install keepalived
      apt:
        name:
          - keepalived
        update_cache: yes

    - name: Open firewall
      command: ufw allow in from any to 224.0.0.18 comment 'keepalived multicast'

    - name: Allow http
      community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp
      
    - name: Allow https
      community.general.ufw:
      rule: allow
      port: '443'
      proto: tcp
