---
- name: Update and upgrade apt packages
  hosts: labb

  tasks:
    - name: Update packages with apt
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      ansible.builtin.apt:
        upgrade: dist