---
- name: Update and upgrade apt packages
  hosts: labb
  become: yes

  tasks:
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
