---
- name: Deploy Docker Compose services
  hosts: "{{ hosts }}"
  become: true
  serial: 1
  vars:
    service: "keepalived"

  tasks:
    - name: Stop keepalived
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: stopped

    - name: Ensure the Git repository directory exists (create if not present)
      file:
        path: "{{ dest }}"
        state: directory
        mode: '0700'

    - name: Update git repository
      git:
        repo: "https://{{ gitlab_token }}:{{ gitlab_token }}@{{ gitlab_repo }}"
        dest: "{{ dest }}"
        version: "main"
        bare: no
        clone: yes
        update: yes
        track_submodules: yes
        force: yes

    - name: Change ownership of the file
      ansible.builtin.file:
        path: "{{ dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: no

    - name: Ensure access.log exists
      file:
        path: "{{ dest }}/access.log"
        state: touch
        mode: "0700"

    - name: access.log file
      command: chmod 600 access.log
      args:
        chdir: "{{ dest }}"   
         
    - name: Ensure acme.json exists
      file:
        path: "{{ dest }}/acme.json"
        state: touch
        mode: "0700"

    - name: acme file
      command: chmod 600 acme.json
      args:
        chdir: "{{ dest }}"

    - name: Pull new docker image
      command: docker compose pull
      args:
        chdir: "{{ dest }}"

    - name: Start/recreate the Docker services
      command: docker compose up -d --force-recreate
      args:
        chdir: "{{ dest }}"

    - name: Sleep for 10
      ansible.builtin.wait_for:
        timeout: 10

    - name: Start keepalived
      ansible.builtin.systemd:
        name: "{{ service }}"
        state: started