all:
  children:
    ubs:
      children:
        infra
          children:
            dns
              hosts:
                10.10.0.10:
                10.10.0.11:
            autoamtion:
              hosts:
                10.10.0.103: