- hosts: "{{ hosts }}"

  tasks:
    - name: Get disk usage
      command: df -h /
      register: disk_usage
      changed_when: false  # Prevents marking the task as changed

    # Teams
    - name: Send Teams message
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        body_format: json
        body:
          title: Disk Space Alert
          text: "Disk space on {{ inventory_hostname }} is above 80%!"
          sections: 
            - facts:
              - name: "Disk Usage"
                value: "{{ disk_usage.stdout_lines[1].split()[4][:-1] | int }}"
        headers:
          Content-Type: application/json
        status_code: 200  # Teams returns 200 for a successful message
      when: disk_usage.stdout_lines[1].split()[4][:-1] | int > 80
