- hosts: "{{ hosts }}"
  become: yes
  gather_facts: false
  serial: 1
  tasks:
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot non essential server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists and inventory_hostname in groups['reboot_individually']
