- hosts: "{{ hosts }}"

  become: yes
  tasks:

  - name: Reboot the server
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
    debug:
      msg: "Running this task on {{ inventory_hostname }}"
    when: inventory_hostname not in groups['reboot_excluded']
