- hosts: "reboot_individually"
  become: yes
  gather_facts: false
  serial: 1
  tasks:
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot non essential server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists

    - name: Wait for service to be running
      service_facts:
      register: result
      until: result.ansible_facts.services[{{ service }}].state == 'running'
      retries: 10
      delay: 5
