- hosts: "{{ hosts }}"

  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists and inventory_hostname not in groups['reboot_excluded']
      
    # Send Discord message when reboot is required
#    - name: Send Discord message
#      uri:
#        url: "{{ discord_webhook_url }}"
#       method: POST
#        body_format: json
#        body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
#        headers:
#          Content-Type: application/json
#        status_code: 204
#      when: reboot_required.stat.exists
#      when: reboot_required.stat.exists and inventory_hostname in groups['reboot_excluded']

    #Teams message
    - name: Send Teams message
      uri:
        url: "{{ teams_webhook_url }}"
        method: POST
        body_format: json
        body:
          text: "Reboot required on {{ inventory_hostname }}"
        headers:
          Content-Type: application/json
        status_code: 200  # Teams returns 200 for a successful message
      when: reboot_required.stat.exists and inventory_hostname in groups['reboot_excluded']
